//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClauseLibrary.Web.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClauseLibrary.Web.App_GlobalResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create clause.
        /// </summary>
        internal static string CreateClauseFail {
            get {
                return ResourceManager.GetString("CreateClauseFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created clause.
        /// </summary>
        internal static string CreateClauseOk {
            get {
                return ResourceManager.GetString("CreateClauseOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete clause.
        /// </summary>
        internal static string DeleteClauseFail {
            get {
                return ResourceManager.GetString("DeleteClauseFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted clause.
        /// </summary>
        internal static string DeleteClauseOk {
            get {
                return ResourceManager.GetString("DeleteClauseOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update clause.
        /// </summary>
        internal static string UpdateClauseFail {
            get {
                return ResourceManager.GetString("UpdateClauseFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clause updated.
        /// </summary>
        internal static string UpdateClauseOk {
            get {
                return ResourceManager.GetString("UpdateClauseOk", resourceCulture);
            }
        }
    }
}
